dist: xenial
language: python
python: "3.7"

cache:
  - pip
services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE="amazonlinux" DOCKER_TAG="2"
    - DOCKER_IMAGE="centos" DOCKER_TAG="7"
    - DOCKER_IMAGE="centos" DOCKER_TAG="8"

script: molecule test
