dist: xenial
language: python
python: "3.7"

cache:
  - pip
services:
  - docker

env:
  matrix:
    - image="amazonlinux" tag="2"
    - image="centos" tag="7"
    - image="centos" tag="8"

script: molecule test
