---
- name: Gracefully test fail2ban configurations
  command: fail2ban-server -t
  register: fail2ban_conf_test
  changed_when:
    - '"OK" in fail2ban_conf_test.stdout'
  failed_when:
    - '"ERROR" in fail2ban_conf_test.stdout'

- name: Reload fail2ban-server
  systemd:
    name: fail2ban.service
    state: reloaded
    enabled: true

- name: Restart fail2ban-server
  systemd:
    name: fail2ban.service
    state: restarted
    enabled: true
